#!/usr/bin/env bash

optstring=":bt"

TEST=0
BUILD=0

while getopts ${optstring} arg; do
  case ${arg} in
    b)
      BUILD=1
      ;;
    t)
      TEST=1
      ;;
  esac
done

if [[ $BUILD == 1 ]]
then
  ant jar
  echo "--------"
fi

shift $((OPTIND-1))
if [[ $TEST == 1 ]]
then
  java -jar ../build/jar/bloxi.jar "$@"
else
  java -jar build/jar/bloxi.jar "$@"
fi
